FROM node:20.18-alpine3.21 AS build
WORKDIR /app
COPY ferreteria_refactor/frontend_web/package*.json ./
RUN npm install --legacy-peer-deps
COPY ferreteria_refactor/frontend_web/ ./
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
RUN npm run build

FROM nginx:1.27-alpine3.21
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]