"""add_warehouse_to_sales

Revision ID: 12fea28e253c
Revises: 75bb9166cb74
Create Date: 2025-12-29 20:20:56.701615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '12fea28e253c'
down_revision: Union[str, Sequence[str], None] = '75bb9166cb74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = inspect(conn)
    
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sales_columns = [c['name'] for c in inspector.get_columns('sales')]
    if 'warehouse_id' not in sales_columns:
        with op.batch_alter_table('sales', schema=None) as batch_op:
            batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_sales_warehouse_id', 'warehouses', ['warehouse_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sales_warehouse_id', type_='foreignkey')
        batch_op.drop_column('warehouse_id')

    # ### end Alembic commands ###
