"""add_price_lists

Revision ID: 1323a07c90a4
Revises: cd44ea688219
Create Date: 2026-01-16 07:25:28.496534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1323a07c90a4'
down_revision: Union[str, Sequence[str], None] = 'cd44ea688219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('requires_auth', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('price_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_lists_id'), ['id'], unique=False)

    op.create_table('product_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price_list_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_prices_id'), ['id'], unique=False)

    # ### DATA SEEDING - Add Base Price List and Migrate Prices ###
    op.execute("INSERT INTO price_lists (name, requires_auth, is_active, created_at) VALUES ('Precio Base (Detal)', FALSE, TRUE, NOW())")
    
    # Copy prices from products.price to product_prices linked to 'Precio Base (Detal)'
    op.execute("""
        INSERT INTO product_prices (product_id, price_list_id, price)
        SELECT id, (SELECT id FROM price_lists WHERE name='Precio Base (Detal)' LIMIT 1), price
        FROM products
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_prices_id'))

    op.drop_table('product_prices')
    with op.batch_alter_table('price_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_lists_id'))

    op.drop_table('price_lists')
    # ### end Alembic commands ###
