"""add_prueba_actualizacion_table

Revision ID: 1727c34e86b5
Revises: b7a931b7db8c
Create Date: 2026-01-03 18:43:33.929573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1727c34e86b5'
down_revision: Union[str, Sequence[str], None] = 'b7a931b7db8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prueba_actualizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prueba_actualizacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prueba_actualizacion_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prueba_actualizacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prueba_actualizacion_id'))

    op.drop_table('prueba_actualizacion')
    # ### end Alembic commands ###
