"""Add warranty configuration

Revision ID: 1b10364deeb0
Revises: ef1f9159fef4
Create Date: 2026-01-12 08:48:34.742826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b10364deeb0'
down_revision: Union[str, Sequence[str], None] = 'ef1f9159fef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum manually
    warranty_unit = sa.Enum('DAYS', 'MONTHS', 'YEARS', name='warrantyunit')
    warranty_unit.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warranty_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('warranty_unit', sa.Enum('DAYS', 'MONTHS', 'YEARS', name='warrantyunit'), nullable=True))
        batch_op.add_column(sa.Column('warranty_notes', sa.String(), nullable=True))

    with op.batch_alter_table('sale_detail_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warranty_expiration_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warranty_expiration_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.drop_column('warranty_expiration_date')

    with op.batch_alter_table('sale_detail_instances', schema=None) as batch_op:
        batch_op.drop_column('warranty_expiration_date')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('warranty_notes')
        batch_op.drop_column('warranty_unit')
        batch_op.drop_column('warranty_duration')

    # Drop enum manually
    warranty_unit = sa.Enum('DAYS', 'MONTHS', 'YEARS', name='warrantyunit')
    warranty_unit.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
