"""add_service_order_tables

Revision ID: 22288a0ebce7
Revises: 4b3bf3c631da
Create Date: 2026-01-04 17:37:56.816344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22288a0ebce7'
down_revision: Union[str, Sequence[str], None] = '4b3bf3c631da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'DIAGNOSING', 'APPROVED', 'IN_PROGRESS', 'READY', 'DELIVERED', 'CANCELLED', name='serviceorderstatus'), nullable=True),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('serial_imei', sa.String(), nullable=False),
    sa.Column('passcode_pattern', sa.Text(), nullable=True),
    sa.Column('problem_description', sa.Text(), nullable=False),
    sa.Column('physical_condition', sa.Text(), nullable=True),
    sa.Column('diagnosis_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_delivery', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_orders_serial_imei'), ['serial_imei'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_orders_ticket_number'), ['ticket_number'], unique=True)

    op.create_table('service_order_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_order_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_order_details_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_order_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_order_details_id'))

    op.drop_table('service_order_details')
    with op.batch_alter_table('service_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_orders_ticket_number'))
        batch_op.drop_index(batch_op.f('ix_service_orders_serial_imei'))
        batch_op.drop_index(batch_op.f('ix_service_orders_id'))

    op.drop_table('service_orders')
    # ### end Alembic commands ###
