"""initial_shared_migration

Revision ID: 318a045a334c
Revises: 
Create Date: 2026-02-10 14:43:16.429747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '318a045a334c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = ('shared',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('schema_name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('has_restaurant_module', sa.Boolean(), nullable=True),
    sa.Column('has_laundry_module', sa.Boolean(), nullable=True),
    sa.Column('has_hardware_module', sa.Boolean(), nullable=True),
    sa.Column('has_services_module', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain'),
    schema='public'
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_tenants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_tenants_schema_name'), ['schema_name'], unique=True)

    op.create_table('tenant_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    with op.batch_alter_table('tenant_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_tenant_payments_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('pin', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'CASHIER', 'WAREHOUSE', 'WAITER', 'KITCHEN', name='userrole'), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('commission_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_public_users_id'), ['id'], unique=False)

    # op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_users_id'))
        batch_op.drop_index(batch_op.f('ix_public_users_email'))

    op.drop_table('users', schema='public')
    with op.batch_alter_table('tenant_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_tenant_payments_id'))

    op.drop_table('tenant_payments', schema='public')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_tenants_schema_name'))
        batch_op.drop_index(batch_op.f('ix_public_tenants_id'))

    op.drop_table('tenants', schema='public')
    # ### end Alembic commands ###
