"""add_prueba_vps_table

Revision ID: 4412401d43cf
Revises: 1727c34e86b5
Create Date: 2026-01-03 18:55:01.096670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4412401d43cf'
down_revision: Union[str, Sequence[str], None] = '1727c34e86b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prueba_vps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prueba_vps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prueba_vps_fecha_creacion'), ['fecha_creacion'], unique=False)
        batch_op.create_index(batch_op.f('ix_prueba_vps_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prueba_vps_titulo'), ['titulo'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prueba_vps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prueba_vps_titulo'))
        batch_op.drop_index(batch_op.f('ix_prueba_vps_id'))
        batch_op.drop_index(batch_op.f('ix_prueba_vps_fecha_creacion'))

    op.drop_table('prueba_vps')
    # ### end Alembic commands ###
