"""Add laundry support to service orders

Revision ID: 441afe556800
Revises: 1323a07c90a4
Create Date: 2026-01-23 18:10:21.996986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441afe556800'
down_revision: Union[str, Sequence[str], None] = '1323a07c90a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # MANUAL FIX: Create ENUM types first
    op.execute("DO $$ BEGIN CREATE TYPE servicetype AS ENUM ('REPAIR', 'LAUNDRY'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE servicepriority AS ENUM ('NORMAL', 'HIGH', 'URGENT'); EXCEPTION WHEN duplicate_object THEN null; END $$;")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
        batch_op.alter_column('incoming_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.alter_column('initial_cash',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('initial_cash_bs',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('final_cash_reported',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('final_cash_reported_bs',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('final_cash_expected',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('final_cash_expected_bs',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('difference',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('difference_bs',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('sale_payments', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
        batch_op.alter_column('total_amount_bs',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('change_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('balance_pending',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('service_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_type', sa.Enum('REPAIR', 'LAUNDRY', name='servicetype'), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Enum('NORMAL', 'HIGH', 'URGENT', name='servicepriority'), nullable=True))
        batch_op.add_column(sa.Column('order_metadata', sa.JSON(), nullable=True))
        batch_op.alter_column('device_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('brand',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('serial_imei',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('problem_description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_orders', schema=None) as batch_op:
        batch_op.alter_column('problem_description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('serial_imei',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('brand',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('device_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('order_metadata')
        batch_op.drop_column('priority')
        batch_op.drop_column('service_type')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('balance_pending',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('change_amount',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total_amount_bs',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('sale_payments', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.alter_column('difference_bs',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('difference',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('final_cash_expected_bs',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('final_cash_expected',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('final_cash_reported_bs',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('final_cash_reported',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('initial_cash_bs',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('initial_cash',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.alter_column('incoming_amount',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
