"""Add tenants table

Revision ID: 447215c5dc51
Revises: 441afe556800
Create Date: 2026-01-24 19:55:57.887606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '447215c5dc51'
down_revision: Union[str, Sequence[str], None] = '441afe556800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if not inspector.has_table("tenants", schema="public"):
        op.create_table('tenants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('schema_name', sa.String(), nullable=False),
        sa.Column('domain', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('config', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('domain'),
        schema='public'
        )
        with op.batch_alter_table('tenants', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_public_tenants_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_public_tenants_schema_name'), ['schema_name'], unique=True)
    else:
        print("[INFO] Skipping creation of public.tenants (already exists)")

    # op.drop_table('alembic_version') # REMOVED DANGEROUS LINE
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('alembic_version', ...) # REMOVED
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_tenants_schema_name'))
        batch_op.drop_index(batch_op.f('ix_public_tenants_id'))

    op.drop_table('tenants', schema='public')
    # ### end Alembic commands ###
