"""dual_transaction_fields

Revision ID: 44943fac8c3e
Revises: 3ea8abdbbb36
Create Date: 2026-01-13 20:05:07.772642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44943fac8c3e'
down_revision: Union[str, Sequence[str], None] = '3ea8abdbbb36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incoming_amount', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('incoming_currency', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('incoming_method', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('incoming_reference', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.drop_column('incoming_reference')
        batch_op.drop_column('incoming_method')
        batch_op.drop_column('incoming_currency')
        batch_op.drop_column('incoming_amount')

    # ### end Alembic commands ###
