"""add_services_module_tables

Revision ID: 4b3bf3c631da
Revises: 877e2507c4c1
Create Date: 2026-01-04 11:06:14.257023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b3bf3c631da'
down_revision: Union[str, Sequence[str], None] = '877e2507c4c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sale_detail_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('percentage_applied', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sale_detail_id'], ['sale_details.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commission_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salesperson_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['salesperson_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission_percentage', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('commission_percentage')

    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('salesperson_id')

    with op.batch_alter_table('commission_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_logs_id'))

    op.drop_table('commission_logs')
    # ### end Alembic commands ###
