"""add_requires_reference

Revision ID: 50263d95b935
Revises: f42ef597515c
Create Date: 2026-01-28 20:35:32.601739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50263d95b935'
down_revision: Union[str, Sequence[str], None] = 'f42ef597515c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_reference', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_column('requires_reference')

    # ### end Alembic commands ###
