"""update_commission_log_structure

Revision ID: 691f30aaa448
Revises: e000fc5b37c7
Create Date: 2026-01-05 09:00:08.599684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '691f30aaa448'
down_revision: Union[str, Sequence[str], None] = 'e000fc5b37c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    """Upgrade schema."""
    # Create Enum Type manually for Postgres
    commission_status = postgresql.ENUM('PENDING', 'PAID', 'CANCELLED', 'VOIDED', name='commissionstatus')
    commission_status.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commission_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_reference', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', 'VOIDED', name='commissionstatus'), nullable=True))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('sale_detail_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('percentage_applied',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    
    # Backfill Data
    op.execute("UPDATE commission_logs SET status = 'PENDING' WHERE status IS NULL")
    op.execute("UPDATE commission_logs SET source_type = 'SALE' WHERE source_type IS NULL")

    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('commission_logs', schema=None) as batch_op:
        batch_op.alter_column('percentage_applied',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('sale_detail_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('notes')
        batch_op.drop_column('paid_at')
        batch_op.drop_column('status')
        batch_op.drop_column('source_reference')
        batch_op.drop_column('source_id')
        batch_op.drop_column('source_type')

    # Drop Enum Type
    commission_status = postgresql.ENUM('PENDING', 'PAID', 'CANCELLED', 'VOIDED', name='commissionstatus')
    commission_status.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
