"""Add_test_auto_migration_table

Revision ID: 6bff1d3c8718
Revises: cc9ffbf36ba0
Create Date: 2025-12-19 11:23:01.247943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bff1d3c8718'
down_revision: Union[str, Sequence[str], None] = 'cc9ffbf36ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    from sqlalchemy import inspect
    inspector = inspect(bind)
    
    if 'test_auto_migration' not in inspector.get_table_names():
        op.create_table('test_auto_migration',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('test_name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_test_auto_migration_id'), 'test_auto_migration', ['id'], unique=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_auto_migration_id'), table_name='test_auto_migration')
    op.drop_table('test_auto_migration')
    # ### end Alembic commands ###
