"""add_transfer_tables

Revision ID: 75bb9166cb74
Revises: c1f1aa74b6ea
Create Date: 2025-12-29 19:56:56.083956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75bb9166cb74'
down_revision: Union[str, Sequence[str], None] = 'c1f1aa74b6ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('target_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['target_warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_transfers_id'), ['id'], unique=False)

    op.create_table('transfer_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['inventory_transfers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_details_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_details_id'))

    op.drop_table('transfer_details')
    with op.batch_alter_table('inventory_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transfers_id'))

    op.drop_table('inventory_transfers')
    # ### end Alembic commands ###
