"""add system messages table

Revision ID: 82548ed2c21a
Revises: 318a045a334c
Create Date: 2026-02-11 11:17:06.377559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82548ed2c21a'
down_revision: Union[str, Sequence[str], None] = '318a045a334c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add check for existing table
    from sqlalchemy.engine.reflection import Inspector
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()

    if 'system_messages' not in tables:
        op.create_table('system_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('level', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='messagelevel'), nullable=True),
        sa.Column('starts_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
        )
        with op.batch_alter_table('system_messages', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_public_system_messages_id'), ['id'], unique=False)

    # op.drop_table('alembic_version')
    with op.batch_alter_table('tenant_payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tenant_payments_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('tenant_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tenant_payments_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])

    # op.create_table('alembic_version', ...)
    with op.batch_alter_table('system_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_system_messages_id'))

    op.drop_table('system_messages', schema='public')
    # ### end Alembic commands ###
