"""increase product_units precision to 4 decimals

Revision ID: 8285d2f7a0d5
Revises: f32cb26a25df
Create Date: 2026-01-05 18:41:19.662840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8285d2f7a0d5'
down_revision: Union[str, Sequence[str], None] = 'f32cb26a25df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_units', schema=None) as batch_op:
        batch_op.alter_column('cost_price',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('price_usd',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_units', schema=None) as batch_op:
        batch_op.alter_column('price_usd',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('cost_price',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)

    # ### end Alembic commands ###
