"""add_tenant_id_to_users

Revision ID: 899ebe39f74e
Revises: eccb326ed61a
Create Date: 2026-02-09 19:18:48.213193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899ebe39f74e'
down_revision: Union[str, Sequence[str], None] = 'eccb326ed61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='public') as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], referent_schema='public')

    # with op.batch_alter_table('audit_logs', schema=None) as batch_op:
    #     batch_op.drop_constraint(batch_op.f('audit_logs_user_id_fkey'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')
    #
    # with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
    #     batch_op.drop_constraint(batch_op.f('cash_sessions_user_id_fkey'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')
    #
    # with op.batch_alter_table('commission_logs', schema=None) as batch_op:
    #     batch_op.drop_constraint(batch_op.f('commission_logs_user_id_fkey'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')
    #
    # with op.batch_alter_table('prueba_vps', schema=None) as batch_op:
    #     batch_op.drop_constraint(batch_op.f('prueba_vps_usuario_id_fkey'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['usuario_id'], ['id'], referent_schema='public')
    #
    # with op.batch_alter_table('restaurant_orders', schema=None) as batch_op:
    #     batch_op.drop_constraint(batch_op.f('restaurant_orders_waiter_id_fkey'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['waiter_id'], ['id'], referent_schema='public')
    #
    # with op.batch_alter_table('sale_details', schema=None) as batch_op:
    #     batch_op.drop_constraint(batch_op.f('sale_details_salesperson_id_fkey'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['salesperson_id'], ['id'], referent_schema='public')
    #
    # with op.batch_alter_table('service_order_details', schema=None) as batch_op:
    #     batch_op.drop_constraint(batch_op.f('service_order_details_technician_id_fkey'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['technician_id'], ['id'], referent_schema='public')
    #
    # with op.batch_alter_table('service_orders', schema=None) as batch_op:
    #     batch_op.drop_constraint(batch_op.f('service_orders_technician_id_fkey'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['technician_id'], ['id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('service_orders_technician_id_fkey'), 'users', ['technician_id'], ['id'])

    with op.batch_alter_table('service_order_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('service_order_details_technician_id_fkey'), 'users', ['technician_id'], ['id'])

    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sale_details_salesperson_id_fkey'), 'users', ['salesperson_id'], ['id'])

    with op.batch_alter_table('restaurant_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('restaurant_orders_waiter_id_fkey'), 'users', ['waiter_id'], ['id'])

    with op.batch_alter_table('prueba_vps', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('prueba_vps_usuario_id_fkey'), 'users', ['usuario_id'], ['id'])

    with op.batch_alter_table('commission_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('commission_logs_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cash_sessions_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('audit_logs_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
