"""add historical cost

Revision ID: a2b2c3d4e5f6
Revises: 2ba48a125ad0
Create Date: 2026-01-01 23:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
from decimal import Decimal

# revision identifiers, used by Alembic.
revision = 'a2b2c3d4e5f6'
down_revision = '2ba48a125ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_details', sa.Column('cost_at_sale', sa.Numeric(precision=14, scale=4), nullable=True, server_default=sa.text("'0.0000'")))
    op.add_column('return_details', sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=True, server_default=sa.text("'0.0000'")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return_details', 'unit_cost')
    op.drop_column('sale_details', 'cost_at_sale')
    # ### end Alembic commands ###
