"""add_notas_rapidas_table

Revision ID: a4041786c431
Revises: 4412401d43cf
Create Date: 2026-01-03 19:52:36.647283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4041786c431'
down_revision: Union[str, Sequence[str], None] = '4412401d43cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas_rapidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=500), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notas_rapidas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notas_rapidas_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notas_rapidas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notas_rapidas_id'))

    op.drop_table('notas_rapidas')
    # ### end Alembic commands ###
