"""add module flags to tenant model

Revision ID: ab44d7190359
Revises: 752a3dbb5ac2
Create Date: 2026-02-04 22:36:12.585357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab44d7190359'
down_revision: Union[str, Sequence[str], None] = '752a3dbb5ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if columns already exist for idempotency
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    # Note: If running for a tenant, the search_path is already set in env.py
    columns = [col['name'] for col in inspector.get_columns('tenants')]
    
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        if 'has_restaurant_module' not in columns:
            batch_op.add_column(sa.Column('has_restaurant_module', sa.Boolean(), nullable=True))
        if 'has_laundry_module' not in columns:
            batch_op.add_column(sa.Column('has_laundry_module', sa.Boolean(), nullable=True))
        if 'has_hardware_module' not in columns:
            batch_op.add_column(sa.Column('has_hardware_module', sa.Boolean(), nullable=True))
        if 'has_services_module' not in columns:
            batch_op.add_column(sa.Column('has_services_module', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('has_services_module')
        batch_op.drop_column('has_hardware_module')
        batch_op.drop_column('has_laundry_module')
        batch_op.drop_column('has_restaurant_module')

    # op.create_table('alembic_version',
    # sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    # )
    # ### end Alembic commands ###
