"""add_warehouses_tables

Revision ID: c1f1aa74b6ea
Revises: 1a2b3c4d5e6f
Create Date: 2025-12-29 19:31:24.140387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1f1aa74b6ea'
down_revision: Union[str, Sequence[str], None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    from sqlalchemy import inspect
    inspector = inspect(conn)
    tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'warehouses' not in tables:
        op.create_table('warehouses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('address', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_main', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('warehouses', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_warehouses_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_warehouses_name'), ['name'], unique=True)

    if 'product_stocks' not in tables:
        op.create_table('product_stocks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('warehouse_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column('location', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('product_stocks', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_product_stocks_id'), ['id'], unique=False)

    if 'test_migration_validation' in tables:
        op.drop_table('test_migration_validation')

    customers_indexes = [ix['name'] for ix in inspector.get_indexes('customers')]
    if 'ix_customers_unique_uuid' not in customers_indexes:
        with op.batch_alter_table('customers', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_customers_unique_uuid'), ['unique_uuid'], unique=True)

    sales_indexes = [ix['name'] for ix in inspector.get_indexes('sales')]
    if 'ix_sales_unique_uuid' not in sales_indexes:
        with op.batch_alter_table('sales', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_sales_unique_uuid'), ['unique_uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_unique_uuid'))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_unique_uuid'))

    op.create_table('test_migration_validation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_string', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('test_integer', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('test_decimal', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('test_boolean', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('test_datetime', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('test_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_migration_validation_pkey'))
    )
    with op.batch_alter_table('product_stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_stocks_id'))

    op.drop_table('product_stocks')
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouses_name'))
        batch_op.drop_index(batch_op.f('ix_warehouses_id'))

    op.drop_table('warehouses')
    # ### end Alembic commands ###
