"""Remove_test_table

Revision ID: cc9ffbf36ba0
Revises: c8152d00b510
Create Date: 2025-12-19 11:06:30.305247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc9ffbf36ba0'
down_revision: Union[str, Sequence[str], None] = 'c8152d00b510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_migration_id'), table_name='test_migration')
    op.drop_table('test_migration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_migration',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_migration_pkey'))
    )
    op.create_index(op.f('ix_test_migration_id'), 'test_migration', ['id'], unique=False)
    # ### end Alembic commands ###
