"""add_description_to_sale_details

Revision ID: e000fc5b37c7
Revises: ed766efe1bea
Create Date: 2026-01-04 19:08:44.636429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e000fc5b37c7'
down_revision: Union[str, Sequence[str], None] = 'ed766efe1bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('quote_details', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
