"""Add sync_status to customers

Revision ID: e0b95dd58b57
Revises: 16a7f80b9c39
Create Date: 2026-02-18 23:03:42.535233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0b95dd58b57'
down_revision: Union[str, Sequence[str], None] = '16a7f80b9c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('alembic_version') # DANGEROUS - Commenting out
    
    # Manually added columns
    op.add_column('customers', sa.Column('sync_status', sa.String(length=20), server_default='SYNCED', nullable=True))
    op.add_column('customers', sa.Column('unique_uuid', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_customers_unique_uuid'), 'customers', ['unique_uuid'], unique=True)
    
    with op.batch_alter_table('admin_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_admin_tasks_id'), ['id'], unique=False)
        # batch_op.drop_constraint(batch_op.f('admin_tasks_created_by_id_fkey'), type_='foreignkey')
        # batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'], referent_schema='public')

    # Commenting out other risky auto-gen changes to focus on Customers
    # with op.batch_alter_table('support_tickets', schema=None) as batch_op:
    #     batch_op.drop_constraint(batch_op.f('support_tickets_tenant_id_fkey'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], referent_schema='public')

    # with op.batch_alter_table('tenant_payments', schema=None) as batch_op:
    #     batch_op.drop_constraint(batch_op.f('tenant_payments_tenant_id_fkey'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], referent_schema='public')

    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.alter_column('is_onboarding_completed',
    #            existing_type=sa.BOOLEAN(),
    #            server_default=None,
    #            existing_nullable=True)
        # batch_op.drop_constraint(batch_op.f('users_tenant_id_fkey'), type_='foreignkey')
        # batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])
        batch_op.alter_column('is_onboarding_completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)

    with op.batch_alter_table('tenant_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tenant_payments_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('support_tickets_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('admin_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('admin_tasks_created_by_id_fkey'), 'users', ['created_by_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_public_admin_tasks_id'))

    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    # ### end Alembic commands ###
