"""add tax_rate

Revision ID: e1b4c19ddaac
Revises: e4c79bc471b0
Create Date: 2025-12-26 19:24:39.862333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b4c19ddaac'
down_revision: Union[str, Sequence[str], None] = 'e4c79bc471b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tax_rate', sa.Numeric(5, 2), nullable=True))
    op.add_column('sale_details', sa.Column('tax_rate', sa.Numeric(5, 2), nullable=True))
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_details', 'tax_rate')
    op.drop_column('products', 'tax_rate')
    # ### end Alembic commands ###
