"""make_email_unique_login

Revision ID: eccb326ed61a
Revises: 741cf6706903
Create Date: 2026-02-09 18:18:28.913055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eccb326ed61a'
down_revision: Union[str, Sequence[str], None] = '741cf6706903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('alembic_version') - REMOVED UNSAFE
    with op.batch_alter_table('tenant_payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tenant_payments_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_public_users_username'))
        batch_op.create_index(batch_op.f('ix_public_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_users_email'))
        batch_op.create_index(batch_op.f('ix_public_users_username'), ['username'], unique=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('tenant_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tenant_payments_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])

    # op.create_table('alembic_version'...) - REMOVED UNSAFE
    # ### end Alembic commands ###
