"""add_serialized_inventory_models

Revision ID: ef1f9159fef4
Revises: 8285d2f7a0d5
Create Date: 2026-01-07 19:54:48.103684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1f9159fef4'
down_revision: Union[str, Sequence[str], None] = '8285d2f7a0d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'SOLD', 'RMA', 'TRANSIT', 'DAMAGED', name='productinstancestatus'), nullable=True),
    sa.Column('cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_instances_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_instances_serial_number'), ['serial_number'], unique=True)

    op.create_table('sale_detail_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_detail_id', sa.Integer(), nullable=False),
    sa.Column('product_instance_id', sa.Integer(), nullable=False),
    sa.Column('warranty_end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_instance_id'], ['product_instances.id'], ),
    sa.ForeignKeyConstraint(['sale_detail_id'], ['sale_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_detail_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_detail_instances_id'), ['id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_imei', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('has_imei')

    with op.batch_alter_table('sale_detail_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_detail_instances_id'))

    op.drop_table('sale_detail_instances')
    with op.batch_alter_table('product_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_instances_serial_number'))
        batch_op.drop_index(batch_op.f('ix_product_instances_id'))

    op.drop_table('product_instances')
    # ### end Alembic commands ###
