"""increase_price_precision_to_4_decimals

Revision ID: f32cb26a25df
Revises: 691f30aaa448
Create Date: 2026-01-05 18:16:17.296068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f32cb26a25df'
down_revision: Union[str, Sequence[str], None] = '691f30aaa448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=False)
    op.alter_column('products', 'price_mayor_1',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('products', 'price_mayor_2',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('products', 'cost_price',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('sale_details', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=False)
    op.alter_column('sale_details', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=False)
    op.alter_column('sale_details', 'cost_at_sale',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_details', 'cost_at_sale',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    op.alter_column('sale_details', 'subtotal',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('sale_details', 'unit_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('products', 'cost_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    op.alter_column('products', 'price_mayor_2',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'price_mayor_1',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
