"""add_waiter_kitchen_roles

Revision ID: ffa6ded4466f
Revises: d3c8e341e329
Create Date: 2026-01-01 19:34:17.795033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffa6ded4466f'
down_revision: Union[str, Sequence[str], None] = 'd3c8e341e329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'WAITER'")
        op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'KITCHEN'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
