"""add_waiter_kitchen_roles

Revision ID: ffa6ded4466f
Revises: d3c8e341e329
Create Date: 2026-01-01 19:34:17.795033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffa6ded4466f'
down_revision: Union[str, Sequence[str], None] = 'd3c8e341e329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    # Check if userrole type exists
    result = conn.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'userrole'"))
    type_exists = result.scalar() is not None

    with op.get_context().autocommit_block():
        if not type_exists:
            # Create type if it doesn't exist (handles databases where Initial was run as String)
            op.execute("CREATE TYPE userrole AS ENUM ('ADMIN', 'CASHIER', 'WAREHOUSE', 'WAITER', 'KITCHEN')")
            # Force conversion of column to use new Enum type
            op.execute("ALTER TABLE users ALTER COLUMN role TYPE userrole USING role::userrole")
        else:
            # If exists, safely add new values
            op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'WAITER'")
            op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'KITCHEN'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
