"""initial_shared_sync

Revision ID: 3f78b77127e6
Revises: 
Create Date: 2026-02-09 11:34:18.436563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f78b77127e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_methods_id'))

    op.drop_table('payment_methods')
    with op.batch_alter_table('restaurant_recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_recipes_id'))

    op.drop_table('restaurant_recipes')
    with op.batch_alter_table('business_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_config_key'))

    op.drop_table('business_config')
    with op.batch_alter_table('price_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_rules_id'))

    op.drop_table('price_rules')
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_movements_id'))

    op.drop_table('cash_movements')
    with op.batch_alter_table('notas_rapidas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notas_rapidas_id'))

    op.drop_table('notas_rapidas')
    with op.batch_alter_table('sale_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_payments_id'))

    op.drop_table('sale_payments')
    with op.batch_alter_table('restaurant_menu_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_menu_items_id'))

    op.drop_table('restaurant_menu_items')
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_returns_id'))

    op.drop_table('returns')
    with op.batch_alter_table('commission_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_logs_id'))

    op.drop_table('commission_logs')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_date'))
        batch_op.drop_index(batch_op.f('ix_sales_id'))
        batch_op.drop_index(batch_op.f('ix_sales_unique_uuid'))

    op.drop_table('sales')
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouses_id'))
        batch_op.drop_index(batch_op.f('ix_warehouses_name'))

    op.drop_table('warehouses')
    with op.batch_alter_table('restaurant_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_orders_id'))

    op.drop_table('restaurant_orders')
    with op.batch_alter_table('service_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_orders_id'))
        batch_op.drop_index(batch_op.f('ix_service_orders_serial_imei'))
        batch_op.drop_index(batch_op.f('ix_service_orders_ticket_number'))

    op.drop_table('service_orders')
    with op.batch_alter_table('kardex', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kardex_id'))

    op.drop_table('kardex')
    with op.batch_alter_table('combo_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_combo_items_id'))

    op.drop_table('combo_items')
    with op.batch_alter_table('product_stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_stocks_id'))

    op.drop_table('product_stocks')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_id'))
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_sku'))

    op.drop_table('products')
    op.drop_table('alembic_version_shared')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('product_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_units_id'))

    op.drop_table('product_units')
    with op.batch_alter_table('prueba_actualizacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prueba_actualizacion_id'))

    op.drop_table('prueba_actualizacion')
    with op.batch_alter_table('business_currencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_currencies_id'))

    op.drop_table('business_currencies')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_id'))

    op.drop_table('payments')
    with op.batch_alter_table('cash_session_currencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_session_currencies_id'))

    op.drop_table('cash_session_currencies')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_id'))
        batch_op.drop_index(batch_op.f('ix_customers_id_number'))
        batch_op.drop_index(batch_op.f('ix_customers_name'))
        batch_op.drop_index(batch_op.f('ix_customers_unique_uuid'))

    op.drop_table('customers')
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_rates_id'))

    op.drop_table('exchange_rates')
    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_items_id'))

    op.drop_table('purchase_items')
    with op.batch_alter_table('restaurant_menu_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_menu_sections_id'))

    op.drop_table('restaurant_menu_sections')
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotes_id'))

    op.drop_table('quotes')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_id'))
        batch_op.drop_index(batch_op.f('ix_suppliers_name'))

    op.drop_table('suppliers')
    with op.batch_alter_table('purchase_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_payments_id'))

    op.drop_table('purchase_payments')
    with op.batch_alter_table('prueba_vps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prueba_vps_fecha_creacion'))
        batch_op.drop_index(batch_op.f('ix_prueba_vps_id'))
        batch_op.drop_index(batch_op.f('ix_prueba_vps_titulo'))

    op.drop_table('prueba_vps')
    with op.batch_alter_table('price_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_lists_id'))

    op.drop_table('price_lists')
    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_details_id'))

    op.drop_table('sale_details')
    with op.batch_alter_table('product_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_instances_id'))
        batch_op.drop_index(batch_op.f('ix_product_instances_serial_number'))

    op.drop_table('product_instances')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_id'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('inventory_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transfers_id'))

    op.drop_table('inventory_transfers')
    with op.batch_alter_table('restaurant_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_order_items_id'))

    op.drop_table('restaurant_order_items')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('return_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_return_details_id'))

    op.drop_table('return_details')
    with op.batch_alter_table('transfer_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_details_id'))

    op.drop_table('transfer_details')
    with op.batch_alter_table('quote_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_details_id'))

    op.drop_table('quote_details')
    with op.batch_alter_table('restaurant_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_tables_id'))
        batch_op.drop_index(batch_op.f('ix_restaurant_tables_zone'))

    op.drop_table('restaurant_tables')
    with op.batch_alter_table('product_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_prices_id'))

    op.drop_table('product_prices')
    with op.batch_alter_table('service_order_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_order_details_id'))

    op.drop_table('service_order_details')
    with op.batch_alter_table('sale_detail_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_detail_instances_id'))

    op.drop_table('sale_detail_instances')
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_sessions_id'))

    op.drop_table('cash_sessions')
    with op.batch_alter_table('test_auto_migration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_auto_migration_id'))

    op.drop_table('test_auto_migration')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_id'))
        batch_op.drop_index(batch_op.f('ix_categories_name'))

    op.drop_table('categories')
    with op.batch_alter_table('tenant_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_tenant_payments_id'), ['id'], unique=False)
        batch_op.drop_constraint(batch_op.f('tenant_payments_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tenant_payments_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_public_tenant_payments_id'))

    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('categories_parent_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey'))
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)

    op.create_table('test_auto_migration',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_auto_migration_pkey'))
    )
    with op.batch_alter_table('test_auto_migration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_auto_migration_id'), ['id'], unique=False)

    op.create_table('cash_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('initial_cash', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('initial_cash_bs', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('final_cash_reported', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('final_cash_reported_bs', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('final_cash_expected', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('final_cash_expected_bs', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('difference', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('difference_bs', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('cash_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cash_sessions_pkey'))
    )
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_sessions_id'), ['id'], unique=False)

    op.create_table('sale_detail_instances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sale_detail_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_instance_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('warranty_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('warranty_expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_instance_id'], ['product_instances.id'], name=op.f('sale_detail_instances_product_instance_id_fkey')),
    sa.ForeignKeyConstraint(['sale_detail_id'], ['sale_details.id'], name=op.f('sale_detail_instances_sale_detail_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sale_detail_instances_pkey'))
    )
    with op.batch_alter_table('sale_detail_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_detail_instances_id'), ['id'], unique=False)

    op.create_table('service_order_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('cost', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=True),
    sa.Column('technician_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_manual', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('observations', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('service_order_details_product_id_fkey')),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], name=op.f('service_order_details_service_order_id_fkey')),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], name=op.f('service_order_details_technician_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('service_order_details_pkey'))
    )
    with op.batch_alter_table('service_order_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_order_details_id'), ['id'], unique=False)

    op.create_table('product_prices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_list_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], name=op.f('product_prices_price_list_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_prices_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_prices_pkey'))
    )
    with op.batch_alter_table('product_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_prices_id'), ['id'], unique=False)

    op.create_table('restaurant_tables',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('zone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('AVAILABLE', 'OCCUPIED', 'RESERVED', 'CLEANING', name='tablestatusdb'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('restaurant_tables_pkey'))
    )
    with op.batch_alter_table('restaurant_tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_tables_zone'), ['zone'], unique=False)
        batch_op.create_index(batch_op.f('ix_restaurant_tables_id'), ['id'], unique=False)

    op.create_table('quote_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quote_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('is_box_sale', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('quote_details_product_id_fkey')),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('quote_details_quote_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('quote_details_pkey'))
    )
    with op.batch_alter_table('quote_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_details_id'), ['id'], unique=False)

    op.create_table('transfer_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transfer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('transfer_details_product_id_fkey')),
    sa.ForeignKeyConstraint(['transfer_id'], ['inventory_transfers.id'], name=op.f('transfer_details_transfer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transfer_details_pkey'))
    )
    with op.batch_alter_table('transfer_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_details_id'), ['id'], unique=False)

    op.create_table('return_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('return_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('unit_cost', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('return_details_product_id_fkey')),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], name=op.f('return_details_return_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('return_details_pkey'))
    )
    with op.batch_alter_table('return_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_details_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('changes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('restaurant_order_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'SENT', 'PREPARING', 'READY', 'SERVED', 'CANCELLED', name='orderitemstatusdb'), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['restaurant_orders.id'], name=op.f('restaurant_order_items_order_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('restaurant_order_items_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('restaurant_order_items_pkey'))
    )
    with op.batch_alter_table('restaurant_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_order_items_id'), ['id'], unique=False)

    op.create_table('inventory_transfers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['warehouses.id'], name=op.f('inventory_transfers_source_warehouse_id_fkey')),
    sa.ForeignKeyConstraint(['target_warehouse_id'], ['warehouses.id'], name=op.f('inventory_transfers_target_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_transfers_pkey'))
    )
    with op.batch_alter_table('inventory_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_transfers_id'), ['id'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purchase_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('paid_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('payment_status', postgresql.ENUM('PENDING', 'PARTIAL', 'PAID', name='paymentstatus'), autoincrement=False, nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('purchase_orders_supplier_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('purchase_orders_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_orders_pkey'))
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_id'), ['id'], unique=False)

    op.create_table('product_instances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('serial_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('AVAILABLE', 'SOLD', 'RMA', 'TRANSIT', 'DAMAGED', name='productinstancestatus'), autoincrement=False, nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_instances_product_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('product_instances_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_instances_pkey'))
    )
    with op.batch_alter_table('product_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_instances_serial_number'), ['serial_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_instances_id'), ['id'], unique=False)

    op.create_table('sale_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('discount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('discount_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tax_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('cost_at_sale', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('subtotal', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('is_box_sale', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('salesperson_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('warranty_expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('sale_details_product_id_fkey')),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('sale_details_sale_id_fkey')),
    sa.ForeignKeyConstraint(['salesperson_id'], ['users.id'], name=op.f('sale_details_salesperson_id_fkey')),
    sa.ForeignKeyConstraint(['unit_id'], ['product_units.id'], name=op.f('sale_details_unit_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sale_details_pkey'))
    )
    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_details_id'), ['id'], unique=False)

    op.create_table('price_lists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('requires_auth', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('price_lists_pkey')),
    sa.UniqueConstraint('name', name=op.f('price_lists_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('price_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_lists_id'), ['id'], unique=False)

    op.create_table('prueba_vps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('contenido', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('precio', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], name=op.f('prueba_vps_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('prueba_vps_pkey'))
    )
    with op.batch_alter_table('prueba_vps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prueba_vps_titulo'), ['titulo'], unique=False)
        batch_op.create_index(batch_op.f('ix_prueba_vps_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prueba_vps_fecha_creacion'), ['fecha_creacion'], unique=False)

    op.create_table('purchase_payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('purchase_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exchange_rate', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase_orders.id'], name=op.f('purchase_payments_purchase_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_payments_pkey'))
    )
    with op.batch_alter_table('purchase_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_payments_id'), ['id'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contact_person', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('current_balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('credit_limit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('payment_terms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('suppliers_pkey'))
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_suppliers_id'), ['id'], unique=False)

    op.create_table('quotes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('quotes_customer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('quotes_pkey'))
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_id'), ['id'], unique=False)

    op.create_table('restaurant_menu_sections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('restaurant_menu_sections_pkey'))
    )
    with op.batch_alter_table('restaurant_menu_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_menu_sections_id'), ['id'], unique=False)

    op.create_table('purchase_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('purchase_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False),
    sa.Column('unit_cost', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('purchase_items_product_id_fkey')),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase_orders.id'], name=op.f('purchase_items_purchase_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_items_pkey'))
    )
    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_items_id'), ['id'], unique=False)

    op.create_table('exchange_rates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('currency_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('currency_symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rate', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('exchange_rates_pkey'))
    )
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_rates_id'), ['id'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('credit_limit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('payment_term_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_blocked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('unique_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('sync_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('customers_pkey'))
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_unique_uuid'), ['unique_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_customers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_id_number'), ['id_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)

    op.create_table('cash_session_currencies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currency_symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('initial_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('final_reported', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('final_expected', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('difference', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['cash_sessions.id'], name=op.f('cash_session_currencies_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cash_session_currencies_pkey'))
    )
    with op.batch_alter_table('cash_session_currencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_session_currencies_id'), ['id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exchange_rate_used', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=True),
    sa.Column('amount_bs', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('payments_customer_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['cash_sessions.id'], name=op.f('payments_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)

    op.create_table('business_currencies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rate', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=True),
    sa.Column('is_anchor', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('business_currencies_pkey'))
    )
    with op.batch_alter_table('business_currencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_currencies_id'), ['id'], unique=False)

    op.create_table('prueba_actualizacion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('prueba_actualizacion_pkey'))
    )
    with op.batch_alter_table('prueba_actualizacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prueba_actualizacion_id'), ['id'], unique=False)

    op.create_table('product_units',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('conversion_factor', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.Column('barcode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cost_price', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('price_usd', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('profit_margin', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('discount_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_discount_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('exchange_rate_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exchange_rate_id'], ['exchange_rates.id'], name=op.f('product_units_exchange_rate_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_units_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_units_pkey'))
    )
    with op.batch_alter_table('product_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_units_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pin', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('ADMIN', 'CASHIER', 'WAREHOUSE', 'WAITER', 'KITCHEN', name='userrole'), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('commission_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('alembic_version_shared',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_shared_pkc'))
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sku', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('price_mayor_1', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('price_mayor_2', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('cost_price', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('profit_margin', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('discount_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_discount_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('tax_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('stock', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=True),
    sa.Column('min_stock', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_box', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('conversion_factor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_combo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exchange_rate_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('has_imei', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('warranty_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('warranty_unit', postgresql.ENUM('DAYS', 'MONTHS', 'YEARS', name='warrantyunit'), autoincrement=False, nullable=True),
    sa.Column('warranty_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_service', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('products_category_id_fkey')),
    sa.ForeignKeyConstraint(['exchange_rate_id'], ['exchange_rates.id'], name=op.f('products_exchange_rate_id_fkey')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('products_supplier_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)

    op.create_table('product_stocks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_stocks_product_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('product_stocks_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_stocks_pkey'))
    )
    with op.batch_alter_table('product_stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_stocks_id'), ['id'], unique=False)

    op.create_table('combo_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('child_product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False),
    sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['child_product_id'], ['products.id'], name=op.f('combo_items_child_product_id_fkey')),
    sa.ForeignKeyConstraint(['parent_product_id'], ['products.id'], name=op.f('combo_items_parent_product_id_fkey')),
    sa.ForeignKeyConstraint(['unit_id'], ['product_units.id'], name=op.f('combo_items_unit_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('combo_items_pkey'))
    )
    with op.batch_alter_table('combo_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_combo_items_id'), ['id'], unique=False)

    op.create_table('kardex',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('movement_type', postgresql.ENUM('PURCHASE', 'SALE', 'ADJUSTMENT', 'RETURN', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', 'EXTERNAL_TRANSFER_IN', 'EXTERNAL_TRANSFER_OUT', name='movementtype'), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('kardex_product_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('kardex_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('kardex_pkey'))
    )
    with op.batch_alter_table('kardex', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kardex_id'), ['id'], unique=False)

    op.create_table('service_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticket_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('technician_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('RECEIVED', 'DIAGNOSING', 'APPROVED', 'IN_PROGRESS', 'READY', 'DELIVERED', 'CANCELLED', name='serviceorderstatus'), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('serial_imei', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('passcode_pattern', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('problem_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('physical_condition', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('diagnosis_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('estimated_delivery', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('service_type', postgresql.ENUM('REPAIR', 'LAUNDRY', name='servicetype'), autoincrement=False, nullable=True),
    sa.Column('priority', postgresql.ENUM('NORMAL', 'HIGH', 'URGENT', name='servicepriority'), autoincrement=False, nullable=True),
    sa.Column('order_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('service_orders_customer_id_fkey')),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], name=op.f('service_orders_technician_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('service_orders_pkey'))
    )
    with op.batch_alter_table('service_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_orders_ticket_number'), ['ticket_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_orders_serial_imei'), ['serial_imei'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_orders_id'), ['id'], unique=False)

    op.create_table('restaurant_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('waiter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'PREPARING', 'READY', 'DELIVERED', 'PAID', 'CANCELLED', name='orderstatusdb'), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('restaurant_orders_sale_id_fkey')),
    sa.ForeignKeyConstraint(['table_id'], ['restaurant_tables.id'], name=op.f('restaurant_orders_table_id_fkey')),
    sa.ForeignKeyConstraint(['waiter_id'], ['users.id'], name=op.f('restaurant_orders_waiter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('restaurant_orders_pkey'))
    )
    with op.batch_alter_table('restaurant_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_orders_id'), ['id'], unique=False)

    op.create_table('warehouses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_main', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('warehouses_pkey'))
    )
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouses_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_warehouses_id'), ['id'], unique=False)

    op.create_table('sales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exchange_rate_used', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=True),
    sa.Column('total_amount_bs', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('change_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('change_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_credit', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('paid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('balance_pending', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unique_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('sync_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_offline_sale', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('sales_customer_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('sales_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sales_pkey'))
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_unique_uuid'), ['unique_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_sales_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_date'), ['date'], unique=False)

    op.create_table('commission_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sale_detail_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('percentage_applied', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'PAID', 'CANCELLED', 'VOIDED', name='commissionstatus'), autoincrement=False, nullable=True),
    sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sale_detail_id'], ['sale_details.id'], name=op.f('commission_logs_sale_detail_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('commission_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('commission_logs_pkey'))
    )
    with op.batch_alter_table('commission_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_logs_id'), ['id'], unique=False)

    op.create_table('returns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_refunded', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('returns_sale_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('returns_pkey'))
    )
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_returns_id'), ['id'], unique=False)

    op.create_table('restaurant_menu_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alias', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price_override', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('restaurant_menu_items_product_id_fkey')),
    sa.ForeignKeyConstraint(['section_id'], ['restaurant_menu_sections.id'], name=op.f('restaurant_menu_items_section_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('restaurant_menu_items_pkey'))
    )
    with op.batch_alter_table('restaurant_menu_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_menu_items_id'), ['id'], unique=False)

    op.create_table('sale_payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exchange_rate', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=True),
    sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('sale_payments_sale_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sale_payments_pkey'))
    )
    with op.batch_alter_table('sale_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_payments_id'), ['id'], unique=False)

    op.create_table('notas_rapidas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('texto', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('completada', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('notas_rapidas_pkey'))
    )
    with op.batch_alter_table('notas_rapidas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notas_rapidas_id'), ['id'], unique=False)

    op.create_table('cash_movements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exchange_rate', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('incoming_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('incoming_currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('incoming_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('incoming_reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['cash_sessions.id'], name=op.f('cash_movements_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cash_movements_pkey'))
    )
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_movements_id'), ['id'], unique=False)

    op.create_table('price_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('min_quantity', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('price_rules_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('price_rules_pkey'))
    )
    with op.batch_alter_table('price_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_rules_id'), ['id'], unique=False)

    op.create_table('business_config',
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('business_config_pkey'))
    )
    with op.batch_alter_table('business_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_config_key'), ['key'], unique=False)

    op.create_table('restaurant_recipes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['products.id'], name=op.f('restaurant_recipes_ingredient_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('restaurant_recipes_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('restaurant_recipes_pkey'))
    )
    with op.batch_alter_table('restaurant_recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_recipes_id'), ['id'], unique=False)

    op.create_table('payment_methods',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('requires_reference', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('payment_methods_pkey')),
    sa.UniqueConstraint('name', name=op.f('payment_methods_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_methods_id'), ['id'], unique=False)

    # ### end Alembic commands ###
