# Solo empaqueta el /dist ya construido en Nginx
# El npm build lo hace GitHub Actions directamente (más rápido y confiable)
FROM nginx:1.27-alpine3.21
COPY dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
