server {
    listen 80;
    server_name localhost;

    # Dónde están los archivos construidos de React
    root /usr/share/nginx/html;
    index index.html;

    # Compresión Gzip para que cargue rápido
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Configuración para Single Page Application (SPA)
    # Si entras a /login, Nginx intenta buscar el archivo login.
    # Si no existe, te devuelve index.html para que React Router maneje la ruta.
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cacheo de archivos estáticos (imágenes, js, css)
    location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    # Página de error 50x
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}