"""add_warehouse_to_kardex_purchases

Revision ID: 2ba48a125ad0
Revises: ffa6ded4466f
Create Date: 2026-01-01 22:46:07.340778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '2ba48a125ad0'
down_revision: Union[str, Sequence[str], None] = 'ffa6ded4466f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'kardex' in tables:
        columns = [c['name'] for c in inspector.get_columns('kardex')]
        if 'warehouse_id' not in columns:
            with op.batch_alter_table('kardex', schema=None) as batch_op:
                batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=True))
                batch_op.create_foreign_key(None, 'warehouses', ['warehouse_id'], ['id'])

    if 'purchase_orders' in tables:
        columns = [c['name'] for c in inspector.get_columns('purchase_orders')]
        if 'warehouse_id' not in columns:
            with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
                batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=True))
                batch_op.create_foreign_key(None, 'warehouses', ['warehouse_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('warehouse_id')

    with op.batch_alter_table('kardex', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('warehouse_id')

    # ### end Alembic commands ###
