"""sync_all_missing_columns

Revision ID: 94f7283605db
Revises: e24d25b92815
Create Date: 2026-01-03 17:41:33.432906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94f7283605db'
down_revision: Union[str, Sequence[str], None] = 'e24d25b92815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('is_anchor', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_currencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_currencies_id'), ['id'], unique=False)

    op.create_table('restaurant_menu_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurant_menu_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_menu_sections_id'), ['id'], unique=False)

    op.create_table('restaurant_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'RESERVED', 'CLEANING', name='tablestatusdb'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurant_tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_tables_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_restaurant_tables_zone'), ['zone'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('cash_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('initial_cash', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('initial_cash_bs', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('final_cash_reported', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('final_cash_reported_bs', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('final_cash_expected', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('final_cash_expected_bs', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('difference_bs', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_sessions_id'), ['id'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'PARTIAL', 'PAID', name='paymentstatus'), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_id'), ['id'], unique=False)

    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_id'), ['id'], unique=False)

    op.create_table('cash_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['cash_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_movements_id'), ['id'], unique=False)

    op.create_table('cash_session_currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('currency_symbol', sa.String(), nullable=False),
    sa.Column('initial_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('final_reported', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('final_expected', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['cash_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_session_currencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_session_currencies_id'), ['id'], unique=False)

    op.create_table('price_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('min_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_rules_id'), ['id'], unique=False)

    op.create_table('purchase_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_items_id'), ['id'], unique=False)

    op.create_table('purchase_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_payments_id'), ['id'], unique=False)

    op.create_table('quote_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_box_sale', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quote_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_details_id'), ['id'], unique=False)

    op.create_table('restaurant_menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('price_override', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['restaurant_menu_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurant_menu_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_menu_items_id'), ['id'], unique=False)

    op.create_table('restaurant_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('waiter_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PREPARING', 'READY', 'DELIVERED', 'PAID', 'CANCELLED', name='orderstatusdb'), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['restaurant_tables.id'], ),
    sa.ForeignKeyConstraint(['waiter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurant_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_orders_id'), ['id'], unique=False)

    op.create_table('restaurant_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurant_recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_recipes_id'), ['id'], unique=False)

    op.create_table('sale_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_payments_id'), ['id'], unique=False)

    op.create_table('restaurant_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'PREPARING', 'READY', 'SERVED', 'CANCELLED', name='orderitemstatusdb'), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['restaurant_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurant_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_order_items_id'), ['id'], unique=False)

    op.drop_table('test_auto_table')
    op.drop_table('porsiacaso2')
    op.drop_table('test_restart_verify')
    op.drop_table('porsiacaso')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)

    with op.batch_alter_table('combo_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_combo_items_child'))
        batch_op.drop_index(batch_op.f('ix_combo_items_parent'))
        batch_op.create_index(batch_op.f('ix_combo_items_id'), ['id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_combo_items_unit_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('combo_items_child_product_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('combo_items_parent_product_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'product_units', ['unit_id'], ['id'])
        batch_op.create_foreign_key(None, 'products', ['child_product_id'], ['id'])
        batch_op.create_foreign_key(None, 'products', ['parent_product_id'], ['id'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))
        batch_op.alter_column('id_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_customers_id_number'))
        batch_op.create_index(batch_op.f('ix_customers_id_number'), ['id_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_name'), ['name'], unique=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('current_debt')

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_methods_id'), ['id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)
        batch_op.drop_column('exchange_rate')

    with op.batch_alter_table('product_stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_stocks_id'), ['id'], unique=False)

    with op.batch_alter_table('product_units', schema=None) as batch_op:
        batch_op.alter_column('conversion_factor',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               type_=sa.Numeric(precision=14, scale=4),
               existing_nullable=False)
        batch_op.alter_column('discount_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('is_discount_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.create_index(batch_op.f('ix_product_units_id'), ['id'], unique=False)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('is_box',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_combo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)

    with op.batch_alter_table('return_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_details_id'), ['id'], unique=False)

    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_refunded', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.create_index(batch_op.f('ix_returns_id'), ['id'], unique=False)

    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discount_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('is_box_sale', sa.Boolean(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_sale_details_unit_id'))
        batch_op.create_index(batch_op.f('ix_sale_details_id'), ['id'], unique=False)
        batch_op.drop_column('unit_price_usd')
        batch_op.drop_column('subtotal_usd')
        batch_op.drop_column('product_name')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('currency', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('exchange_rate_used', sa.Numeric(precision=14, scale=4), nullable=True))
        batch_op.add_column(sa.Column('total_amount_bs', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('is_credit', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('balance_pending', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_id'), ['id'], unique=False)
        batch_op.drop_constraint(batch_op.f('sales_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('total_amount_ves')
        batch_op.drop_column('status')
        batch_op.drop_column('total_amount_usd')
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_id'), ['id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('ADMIN', 'CASHIER', 'WAREHOUSE', 'WAITER', 'KITCHEN', name='userrole'),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouses_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouses_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('ADMIN', 'CASHIER', 'WAREHOUSE', 'WAITER', 'KITCHEN', name='userrole'),
               nullable=False)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_id'))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('total_amount_usd', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', postgresql.ENUM('PENDING', 'PAID', 'CANCELLED', 'REFUNDED', name='salestatus'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_amount_ves', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('sales_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_sales_id'))
        batch_op.drop_index(batch_op.f('ix_sales_date'))
        batch_op.drop_column('balance_pending')
        batch_op.drop_column('due_date')
        batch_op.drop_column('paid')
        batch_op.drop_column('is_credit')
        batch_op.drop_column('total_amount_bs')
        batch_op.drop_column('exchange_rate_used')
        batch_op.drop_column('currency')
        batch_op.drop_column('total_amount')

    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subtotal_usd', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('unit_price_usd', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_sale_details_id'))
        batch_op.create_index(batch_op.f('idx_sale_details_unit_id'), ['unit_id'], unique=False)
        batch_op.drop_column('is_box_sale')
        batch_op.drop_column('subtotal')
        batch_op.drop_column('discount_type')
        batch_op.drop_column('discount')
        batch_op.drop_column('unit_price')

    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_returns_id'))
        batch_op.drop_column('total_refunded')

    with op.batch_alter_table('return_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_return_details_id'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_id'))
        batch_op.alter_column('is_combo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_box',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('product_units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_product_units_id'))
        batch_op.alter_column('is_discount_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('discount_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('conversion_factor',
               existing_type=sa.Numeric(precision=14, scale=4),
               type_=sa.NUMERIC(precision=12, scale=3),
               existing_nullable=False)

    with op.batch_alter_table('product_stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_stocks_id'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exchange_rate', sa.NUMERIC(precision=14, scale=4), server_default=sa.text('1.0000'), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_payments_id'))

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_methods_id'))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_debt', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_customers_name'))
        batch_op.drop_index(batch_op.f('ix_customers_id'))
        batch_op.drop_index(batch_op.f('ix_customers_id_number'))
        batch_op.create_index(batch_op.f('ix_customers_id_number'), ['id_number'], unique=True)
        batch_op.alter_column('id_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('is_blocked')

    with op.batch_alter_table('combo_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('combo_items_parent_product_id_fkey'), 'products', ['parent_product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('combo_items_child_product_id_fkey'), 'products', ['child_product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_combo_items_unit_id'), 'product_units', ['unit_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_combo_items_id'))
        batch_op.create_index(batch_op.f('ix_combo_items_parent'), ['parent_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_combo_items_child'), ['child_product_id'], unique=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_id'))

    op.create_table('porsiacaso',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('porsiacaso_pkey'))
    )
    op.create_table('test_restart_verify',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'ok'::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_restart_verify_pkey'))
    )
    op.create_table('porsiacaso2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('porsiacaso2_pkey'))
    )
    op.create_table('test_auto_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('info', sa.VARCHAR(length=50), server_default=sa.text("'auto_migrated'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_auto_table_pkey'))
    )
    with op.batch_alter_table('restaurant_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_order_items_id'))

    op.drop_table('restaurant_order_items')
    with op.batch_alter_table('sale_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_payments_id'))

    op.drop_table('sale_payments')
    with op.batch_alter_table('restaurant_recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_recipes_id'))

    op.drop_table('restaurant_recipes')
    with op.batch_alter_table('restaurant_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_orders_id'))

    op.drop_table('restaurant_orders')
    with op.batch_alter_table('restaurant_menu_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_menu_items_id'))

    op.drop_table('restaurant_menu_items')
    with op.batch_alter_table('quote_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_details_id'))

    op.drop_table('quote_details')
    with op.batch_alter_table('purchase_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_payments_id'))

    op.drop_table('purchase_payments')
    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_items_id'))

    op.drop_table('purchase_items')
    with op.batch_alter_table('price_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_rules_id'))

    op.drop_table('price_rules')
    with op.batch_alter_table('cash_session_currencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_session_currencies_id'))

    op.drop_table('cash_session_currencies')
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_movements_id'))

    op.drop_table('cash_movements')
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotes_id'))

    op.drop_table('quotes')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_id'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_sessions_id'))

    op.drop_table('cash_sessions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('restaurant_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_tables_zone'))
        batch_op.drop_index(batch_op.f('ix_restaurant_tables_id'))

    op.drop_table('restaurant_tables')
    with op.batch_alter_table('restaurant_menu_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_menu_sections_id'))

    op.drop_table('restaurant_menu_sections')
    with op.batch_alter_table('business_currencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_currencies_id'))

    op.drop_table('business_currencies')
    # ### end Alembic commands ###
